version: "3.7"

services:
  silverbullet:
    container_name: silverbullet
    image: zefhemel/silverbullet:latest
    restart: unless-stopped
    volumes:
      - ${DATAFOLDER}:/space
    environment:
      SB_USER: "${USERNAME}:${PASSWORD}"
    networks:
      - proxy

networks:
  proxy:
    external: true
